# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=512)),
                ('answer', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Python'), (2, 'Music'), (3, 'Astronomy')])),
                ('grade', models.IntegerField(choices=[(0, 'easy'), (1, 'normal'), (2, 'hard'), (3, 'unfair'), (4, 'tricky')], default=0)),
            ],
        ),
    ]
