# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Muzyka'), (3, 'Astronomia')]),
        ),
    ]
