# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20170116_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
