# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='comment',
            new_name='comment_correct',
        ),
        migrations.AddField(
            model_name='question',
            name='comment_wrong',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
