# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0004_auto_20170116_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mug_shot', models.ImageField(upload_to='static/npcs')),
                ('came_from', models.CharField(max_length=128)),
                ('occupation', models.CharField(max_length=128)),
                ('interested', models.CharField(max_length=128)),
                ('level', models.SmallIntegerField(choices=[(1, 'tabloid'), (2, 'regular'), (3, 'yoda')])),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mug_shot', models.ImageField(blank=True, null=True, upload_to='static/players')),
                ('came_from', models.CharField(max_length=128)),
                ('occupation', models.CharField(max_length=128)),
                ('interested', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Muzyka'), (3, 'Astronomia')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.SmallIntegerField(choices=[(0, 'easy'), (1, 'normal'), (2, 'hard'), (3, 'unfair'), (4, 'tricky')], default=0),
        ),
    ]
