# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20170116_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcplayer',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'gump'), (2, 'joey'), (3, 'ross'), (4, 'sheldon')]),
        ),
    ]
