# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_auto_20170118_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcplayer',
            name='mug_shot',
            field=models.ImageField(upload_to='static/media/npcs'),
        ),
    ]
