# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_auto_20170119_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcplayer',
            name='mug_shot',
            field=models.ImageField(upload_to='static/npcs'),
        ),
    ]
