# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0024_tadeuszsznuk_the_girl'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcplayer',
            name='character',
            field=models.SmallIntegerField(choices=[(0, 'random'), (1, 'vicious'), (2, 'next')], default=0),
        ),
    ]
